### ISSUE TITLE
how to create a attachments programatically and add to slot ?

### ISSUE THREAD

**Issue by msgopinath** [pixijs/pixi-spine#201]

**Comment by ivanpopelyshev** [comment]
There's no way to do it for now, but you can try.

I only know how to switch specific attachment texture.

**Comment by ivanpopelyshev** [comment]
1. You can ask at esotericSoftware forums, I dont know of any spine runtimes that support "add attachment in runtime" feature.
2. You can make an example that I'll put in https://github.com/pixijs/pixi-spine/tree/master/examples

I certainly would not do it personally unless you confirm that your case cant be solved with something like 
1. add temporary attachment from spine editor, and change the texture in runtime
2. just add a pixi child to one of slotcontainers, `spineObj.slotContainers[spineObj.skeleton.findSlotIndex('mySlot'].addChild(...)`

**Comment by msgopinath** [comment]
spineObject.slotContainers[i].removeChildren();
spineObject.slotContainers[i].addChild(objectToAttach);
thats how we are do it , the problem is new object added but old children's are not removed and still exist not cleared any tips for this..Or else we can have some empty place holder instead of visible object to replace that one option :)

**Comment by ivanpopelyshev** [comment]
hack the texture, put PIXI.Texture.EMPTY in that attachment.

**Comment by msgopinath** [comment]
Thanks handy nice tricks!!

**Comment by ivanpopelyshev** [comment]
Those tricks were invented because people really want more than just Spine Runtime API :)

**Comment by msgopinath** [comment]
one quick question: can pixi-spine handle binary format exported spine project?

**Comment by ivanpopelyshev** [comment]
No, `spine-ts` cant, and `pixi-spine` does not have the necessary code too.

**Comment by msgopinath** [comment]
Any plan add support in near future?

**Comment by phloud** [comment]
thx ivan, I've used the spine.hackTextureBySlotName before and came across this today while looking yet again for a way to work with spine and pixi and attachments. the PIXI.Texture.EMPTY works great! thx for all the work on this, it certainly makes for some nice results.

**Comment by ivanpopelyshev** [comment]
thanks, thats also good idea :)
