### ISSUE TITLE
incorrect offset on joints

### ISSUE THREAD

**Issue by septinite** [pixijs/pixi-spine#58]
I'm giving pixi + spine a test run and have run into some issues right off the bat with some of spine's example assets where the joints are oddly offset, and was hoping y'all could point me somewhere to correct.

example repo here: https://github.com/septinite/test_spine_001

and screenshot here:

![image](https://cloud.githubusercontent.com/assets/2975221/10341213/d748b040-6ce1-11e5-828a-dfcb5ae3edb7.png)

**Comment by ivanpopelyshev** [comment]
Hey! thank you, i'll look at it today

**Comment by shavenrat** [comment]
When you generate the Atlas disable "Allow Rotation" from Texture Packer...

**Comment by septinite** [comment]
well, that was easy! thank you much!

**Comment by ivanpopelyshev** [comment]
@shavenrat Wait, I think i fixed that in previous commit. Can you try latest pixi-spine.js from this repo? I suppose that you used npm latest.

**Comment by ivanpopelyshev** [comment]
@shavenrat ok, I just uploaded pixi-spine v1.0.6 on npm, please run your example on that.

**Comment by septinite** [comment]
@ivanpopelyshev ran my example with 1.0.6 and its looking good for the dragon without the texturepacker rotation unchecked.

however, after plugging in the hoverboard spineboy example his mouth attachments are a bit all over the place. is there a similar atlas issue at play here?

**Comment by ivanpopelyshev** [comment]
@septinite that's not atlas issues. Pixi-spine configures pixi.js, and pixi is calculating all coordinates. Formulaes are different, that's why we still have those kind of problems. Rotation setting is one of the problems.

**Comment by shavenrat** [comment]
@ivanpopelyshev I was using a version forked from 1.0.4; I'm now on commit d4787bd1fcb5a599b23ffa9c9930e228061b7517, but I still have some issues when using allow rotation with assets that are mirrored within spine (i.e. when a scale value is set to -1.0).
